apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
  labels:
    app: apache
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80   # exposed port in the cluster
      targetPort: 80  # container port 
  type: ClusterIP