# This is a Role definition in Kubernetes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # Name of the Role
  name: example-role
  # Namespace where the Role will be applied
  namespace: default
rules:                                # List of permissions
  - apiGroups: [""]                   # List of rules associated with this Role
    resources: ["pods"]               # List of resources this Role can access
    verbs: ["get", "watch", "list"]   # List of verbs (actions) this Role can perform on the resources
