apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-88-cluster-88-cluster
  region: eu-north-1
  # namespace: eks-88-cluster

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: eks-key