apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql-app
  labels:
    app: mysql
spec:
  clusterIP: None
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
