apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXktdXNlcm5hbWU=  # base64 encoded value of 'my-username'
  password: bXktcGFzc3dvcmQ=  # base64 encoded value of 'my-password'